### ISSUE TITLE
[ WARN:0@5.862] ……can't open/read file: check file path/integrity

### ISSUE THREAD

**Issue by SSSSamZhu** [ouc-ocean-group/RRNet#10]
Hi, I have recently encountered a problem in reproducing the work of the author.
`[ WARN:0@4.047] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/mnt/Sam_zhu/RRnet/data/DronesDET/train/roadmap/0000257_00001_d_0000042.jpg'): can't open/read file: check file path/integrity
[ WARN:0@6.205] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/mnt/Sam_zhu/RRnet/data/DronesDET/train/roadmap/0000331_01401_d_0000831.jpg'): can't open/read file: check file path/integrity
[ WARN:0@5.862] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/mnt/Sam_zhu/RRnet/data/DronesDET/train/roadmap/9999955_00000_d_0000015.jpg'): can't open/read file: check file path/integrity`
Is this caused by a problem with my dataset? There is no `roadmap` folder in the dataset I downloaded, which makes me confused.
`(base) XX@XX:/mnt/Sam_zhu/RRnet/data/DronesDET$ ls
train  val  VisDrone2019-DET-val.zip
(base) XX@XX:/mnt/Sam_zhu/RRnet/data/DronesDET$ cd train/
(base) XX@XX:/mnt/Sam_zhu/RRnet/data/DronesDET/train$ lsannotations  images
`

**Comment by GeoffreyChen777** [comment]
If you wish to use the AdaResampling data augmentation, you need to use a semantic segmentation to generate the road segmentation map (roadmap).

We use the pretrained deeplab to do that.

You can choose whichever you like to do this.

If you don't want to use this augmentation, just disable the roadmap loading and remove the augmentation:

https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/configs/rrnet_config.py#L39

https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/configs/rrnet_config.py#L44

**Comment by SSSSamZhu** [comment]
Thanks for your quick answer. I will close this issue.
