### ISSUE TITLE
Can't download hourglass pretrained model

### ISSUE THREAD

**Issue by xdeng7** [ouc-ocean-group/RRNet#3]
While downloading the pretrained backbone, it said tries failure.

**Comment by GeoffreyChen777** [comment]
@xdeng7 

Hi, xueqing, I have asked my ex-colleague to give you a google drive link of the pretrained backbone model. Please wait for his reply.

**Comment by xdeng7** [comment]
Thank you for your help.

**Comment by lqxisok** [comment]
@xdeng7  We have uploaded the pretrained backbone weight on the google drive. Link is here [hourglass.pth](https://drive.google.com/file/d/1VYqGhlh_nnSJpUcIu7SPy0Q9AU4EW8Ng/view?usp=sharing)

**Comment by xdeng7** [comment]
Thank you so much. It seems there's restricted permission to download the file. I've made the request, please approve.

**Comment by lqxisok** [comment]
The link has been upgraded.

**Comment by xdeng7** [comment]
Thank you.

**Comment by 48694042** [comment]
@lqxisok 您好，抱歉打扰您。
报错的内容如下：
File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
return _load(f, map_location, pickle_module, **pickle_load_args)
File "/data/home/scv6002/.conda/envs/scz0829/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.
请问我应该对我的hourglass.pth做何改动？

**Comment by GeoffreyChen777** [comment]
@48694042
Could you please tell us your Python and Pytorch version?

**Comment by 48694042** [comment]
> @GeoffreyChen777 
Python：3.7，Pytorch：1.1.0

**Comment by GeoffreyChen777** [comment]
@48694042 

Sorry, I cannot reproduce your problem. I've test it with py3.7 and torch1.1.0 on my device. I can load the pretrained model without errors. Thus, we cannot help you more, nothing is wrong with our pretrained weight.

![image](https://user-images.githubusercontent.com/14183213/148131155-7314194f-b179-4dff-ad08-7ae9fb60ddda.png)
