### ISSUE TITLE
Not able to download pre-trained network

### ISSUE THREAD

**Issue by larserikfagernaes** [ouc-ocean-group/RRNet#4]
Hi! 

I tried to access the pre-trained network at: hdfs://192.168.193.1:9000/data/models/geo/hourglass.pth, but it was not accessible. How can I get it?

**Comment by GeoffreyChen777** [comment]
> Hi!
> 
> I tried to access the pre-trained network at: hdfs://192.168.193.1:9000/data/models/geo/hourglass.pth, but it was not accessible. How can I get it?

Hi, you can go to CenterNet repo to download the pretrained backbone weight.
