### ISSUE TITLE
AdaResampling

### ISSUE THREAD

**Issue by BEVISjyy** [ouc-ocean-group/RRNet#5]
作者您好！请问您论文中提到的AdaResampling部分的code在哪里呢？

**Comment by GeoffreyChen777** [comment]
https://github.com/ouc-ocean-group/RRNet/blob/353058ec642738bf6956f5fd56501075f2571894/datasets/transforms/functional.py#L356

@BEVISjyy 抱歉函数名是当时打比赛时候玩的梗= = 略显不专业了。。

**Comment by BEVISjyy** [comment]
感谢告知！
