### ISSUE TITLE
Enhanced images by AdaResampling

### ISSUE THREAD

**Issue by chensongloose** [ouc-ocean-group/RRNet#9]
你好，想问一下通过AdaResampling增强之后的数据集保存的位置在哪儿呢，在代码里没看到

**Comment by GeoffreyChen777** [comment]
没有保存直接送去训练

**Comment by chensongloose** [comment]
如果我想保存增强后的图片，请问应该修改那个部分的代码呢。感谢大佬回答


| |
chensongloose
|
|
***@***.***
|
On 11/3/2022 ***@***.***> wrote：

没有保存直接送去训练

**Comment by GeoffreyChen777** [comment]
#5

**Comment by chensongloose** [comment]
您好，请问可以提供下“roadmap”数据集的下载链接或者生成脚本吗。感激大佬百忙中抽空帮助
| |
chensongloose
|
|
***@***.***
|
On 11/3/2022 ***@***.***> wrote：

#5

**Comment by GeoffreyChen777** [comment]
随便任何分割网络都可以做到，我已离开原学校许久，拿不到数据了

**Comment by chensongloose** [comment]
您好，想请问下roadmap数据集格式是分割网络产生的图片吗？（论文里提到的中值滤波后的图片）。我现在遇到的问题是roadmap中保存了通过分割网络分割后得到的图片，但是重采样后发现目标物体并不只生成在分割区域内。


| |
chensongloose
|
|
***@***.***
|
On 11/3/2022 ***@***.***> wrote：

随便任何分割网络都可以做到，我已离开原学校许久，拿不到数据了

**Comment by GeoffreyChen777** [comment]
是分割之后的结果，并且使用滤波过滤掉一定的噪音点。

**Comment by chensongloose** [comment]
格式是图片形式吗


| |
chensongloose
|
|
***@***.***
|
On 11/18/2022 ***@***.***> wrote：

是分割之后的结果，并且使用滤波过滤掉一定的噪音点。

**Comment by GeoffreyChen777** [comment]
嗯嗯应该是的，我记得应该是0/1值的吧

**Comment by GeoffreyChen777** [comment]
根据这两行，可以看到

https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/datasets/transforms/functional.py#L361-L362

所有非零的点都是合法区域。也就是说，路面是1，其他为0。

按照这个规则去准备 roadmap 就可以了

**Comment by chensongloose** [comment]
感谢您的帮助。现在发现输出的图片宽高相较于输入图片的宽高放大了1.5倍，请问在哪里修改这个问题呢。（输入图片是1920*1080，重采样以后得到的图片像素是2880*1620）
| |
chensongloose
|
|
***@***.***
|
On 11/18/2022 ***@***.***> wrote：

根据这两行，可以看到

https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/datasets/transforms/functional.py#L361-L362

所有非零的点都是合法区域。也就是说，路面是1，其他为0。

按照这个规则去准备 roadmap 就可以了

**Comment by GeoffreyChen777** [comment]
https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/configs/rrnet_config.py#L41
________________________________
